/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { ILoginInformation } from "./interfaces/login-information.generated"; 

export class AuthDao extends GraphDao {
    
    /**
     * returns your current login status
     * */
    public getStatus(): Promise<ILoginInformation> {
        const query = `query auth_getStatus {
    auth_getStatus
     { ssn parent { parentSsn
 createdAt
 address
 address2
 zipcode
 city
 firstName
 lastName
 email
 phone
 lat
 lng }  user { userSsn
 blocked
 createdAt
 email
 phone
 firstName
 lastName
 loginTime
 comment
 location
 occupation
 avatar
 workplace } } 
}`;
        return this.post({ query, variables: {  } });
    }

    
    /**
     * Kills the session and logs out current user
     * */
    public logout(): Promise<boolean> {
        const query = `mutation auth_logout {
    auth_logout
    
}`;
        return this.post({ query, variables: {  } });
    }

}
