/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { IChoiceWithRanks } from "./interfaces/choice-with-ranks.generated"; 

export class ChoiceDao extends GraphDao {
    
    /**
     * List all choices &amp; ranks for a given studentSsn, require operator right
     * */
    public listForStudent(studentSsn: string): Promise<IChoiceWithRanks[]> {
        const query = `query choice_listForStudent($studentSsn: String) {
    choice_listForStudent(studentSsn: $studentSsn)
     { choiceId
 createdAt
 parentSsn
 studentSsn
 studentFirstName
 studentLastName
 parentFirstName
 parentLastName } 
}`;
        return this.post({ query, variables: { studentSsn: studentSsn } });
    }

    
    /**
     * Your child should continue in current school. Requires logged in as parent. studentSsn must belong to you
     * */
    public continueCurrentSchool(studentSsn: string): Promise<IChoiceWithRanks[]> {
        const query = `mutation choice_continueCurrentSchool($studentSsn: String) {
    choice_continueCurrentSchool(studentSsn: $studentSsn)
     { choiceId
 createdAt
 parentSsn
 studentSsn
 studentFirstName
 studentLastName
 parentFirstName
 parentLastName } 
}`;
        return this.post({ query, variables: { studentSsn: studentSsn } });
    }

}
