/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { ICommunicationTemplate } from "./interfaces/communication-template.generated"; 

export class CommunicationtemplateDao extends GraphDao {
    
    /**
     * List all, returns for municipality if not root
     * */
    public listAll = (): Promise<ICommunicationTemplate[]> => {
        const query = `query communicationtemplate_listAll {
    communicationtemplate_listAll
     { undefined } 
}`;
        return this.post({ query, variables: {  } });
    }

    
    /**
     * Creates a new template
     * */
    public createTemplate = (template: ICommunicationTemplate): Promise<void> => {
        const query = `mutation communicationtemplate_createTemplate($template: CommunicationTemplateInput) {
    communicationtemplate_createTemplate(template: $template)
     { undefined } 
}`;
        return this.post({ query, variables: { template: template } });
    }

    
    /**
     * Get user given username, requires operator right
     * */
    public updateTemplate = (template: ICommunicationTemplate): Promise<void> => {
        const query = `mutation communicationtemplate_updateTemplate($template: CommunicationTemplateInput) {
    communicationtemplate_updateTemplate(template: $template)
     { undefined } 
}`;
        return this.post({ query, variables: { template: template } });
    }

}
