/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";


export class DebugDao extends GraphDao {
    
    /**
     * Cheat way to log in as a user, does not work in prod environment
     * */
    public logMeIn(userSsn: string): Promise<boolean> {
        const query = `mutation debug_logMeIn($userSsn: String) {
    debug_logMeIn(userSsn: $userSsn)
    
}`;
        return this.post({ query, variables: { userSsn: userSsn } });
    }

}
