/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { IDistance } from "./interfaces/distance.generated"; 

export class DistanceDao extends GraphDao {
    
    /**
     * List all distances in your municipality
     * */
    public listDistances = (): Promise<IDistance[]> => {
        const query = `query distance_listDistances {
    distance_listDistances
     { undefined } 
}`;
        return this.post({ query, variables: {  } });
    }

    
    /**
     * List all distances for student in your municipality
     * */
    public listForStudent = (studentSsn: string): Promise<IDistance[]> => {
        const query = `query distance_listForStudent($studentSsn: String) {
    distance_listForStudent(studentSsn: $studentSsn)
     { undefined } 
}`;
        return this.post({ query, variables: { studentSsn: studentSsn } });
    }

    
    /**
     * Uploads a batch of distsances to the db
     * */
    public addDistances = (distances: IDistance[]): Promise<void> => {
        const query = `mutation distance_addDistances($distances: [DistanceInput]) {
    distance_addDistances(distances: $distances)
     { undefined } 
}`;
        return this.post({ query, variables: { distances: distances } });
    }

}
