/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { IViewMoveRequestParentInfo } from "./interfaces/view-move-request-parent-info.generated"; 

export class MoveRequestDao extends GraphDao {
    
    /**
     * 
     * */
    public listLatestWithParent(): Promise<IViewMoveRequestParentInfo[]> {
        const query = `query moveRequest_listLatestWithParent {
    moveRequest_listLatestWithParent
     { moveRequestId
 createdAt
 createdBy
 studentSsn
 fileId
 address
 address2
 zipcode
 city
 requestStatus
 userComment
 canceled
 phone
 email
 firstName
 lastName
 userFirstName
 userLastName } 
}`;
        return this.post({ query, variables: {  } });
    }

}
