/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { IParent } from "./interfaces/parent.generated"; 

export class ParentDao extends GraphDao {
    
    /**
     * Get paretnt object associated with logged in user. Requires logged in as a parent
     * */
    public getMyselfParent(): Promise<IParent> {
        const query = `query parent_getMyselfParent {
    parent_getMyselfParent
     { parentSsn
 createdAt
 address
 address2
 zipcode
 city
 firstName
 lastName
 email
 phone
 lat
 lng } 
}`;
        return this.post({ query, variables: {  } });
    }

    
    /**
     * Get parent for parentSsn, requires operator right
     * */
    public getParent(parentSsn: string): Promise<IParent> {
        const query = `query parent_getParent($parentSsn: String) {
    parent_getParent(parentSsn: $parentSsn)
     { parentSsn
 createdAt
 address
 address2
 zipcode
 city
 firstName
 lastName
 email
 phone
 lat
 lng } 
}`;
        return this.post({ query, variables: { parentSsn: parentSsn } });
    }

    
    /**
     * Returns array with all Parents, requires operator right
     * */
    public listParents(): Promise<IParent[]> {
        const query = `query parent_listParents {
    parent_listParents
     { parentSsn
 createdAt
 address
 address2
 zipcode
 city
 firstName
 lastName
 email
 phone
 lat
 lng } 
}`;
        return this.post({ query, variables: {  } });
    }

}
