/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { IPlacementRound } from "./interfaces/placement-round.generated"; 

export class PlacementRoundDao extends GraphDao {
    
    /**
     * Get the currently active round
     * */
    public getDefaultRound = (): Promise<IPlacementRound> => {
        const query = `query placementRound_getDefaultRound {
    placementRound_getDefaultRound
     { undefined } 
}`;
        return this.post({ query, variables: {  } });
    }

    
    /**
     * List all rounds municipality
     * */
    public listRounds = (): Promise<IPlacementRound[]> => {
        const query = `query placementRound_listRounds {
    placementRound_listRounds
     { undefined } 
}`;
        return this.post({ query, variables: {  } });
    }

    
    /**
     * Insert a new placement round
     * */
    public createNewRound = (placementRound: IPlacementRound): Promise<void> => {
        const query = `mutation placementRound_createNewRound($placementRound: PlacementRoundInput) {
    placementRound_createNewRound(placementRound: $placementRound)
     { undefined } 
}`;
        return this.post({ query, variables: { placementRound: placementRound } });
    }

}
