/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { IRestrictedChoosability } from "./interfaces/restricted-choosability.generated"; 

export class RestrictedChoosabilityDao extends GraphDao {
    
    /**
     * Send in a list of resticted choosability objects
     * */
    public listForRound = (placementRoundId: number): Promise<IRestrictedChoosability[]> => {
        const query = `query restrictedChoosability_listForRound($placementRoundId: Int) {
    restrictedChoosability_listForRound(placementRoundId: $placementRoundId)
     { undefined } 
}`;
        return this.post({ query, variables: { placementRoundId: placementRoundId } });
    }

    
    /**
     * bulk add items
     * */
    public bulkInsert = (items: IRestrictedChoosability[]): Promise<void> => {
        const query = `mutation restrictedChoosability_bulkInsert($items: [RestrictedChoosabilityInput]) {
    restrictedChoosability_bulkInsert(items: $items)
     { undefined } 
}`;
        return this.post({ query, variables: { items: items } });
    }

}
