/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { ISchool } from "./interfaces/school.generated"; 

export class SchoolDao extends GraphDao {
    
    /**
     * Return a schools given int schoolId, logged in user
     * */
    public getSchool(schoolId: number): Promise<ISchool> {
        const query = `query school_getSchool($schoolId: Int) {
    school_getSchool(schoolId: $schoolId)
     { schoolId
 name
 municipality
 area
 address
 address2
 zipcode
 city
 info
 lat
 lng
 statute
 specialProgram
 homepage
 lowestGrade
 highestGrade } 
}`;
        return this.post({ query, variables: { schoolId: schoolId } });
    }

    
    /**
     * Return an array of schools, logged in user
     * */
    public listAll(): Promise<ISchool[]> {
        const query = `query school_listAll {
    school_listAll
     { schoolId
 name
 municipality
 area
 address
 address2
 zipcode
 city
 info
 lat
 lng
 statute
 specialProgram
 homepage
 lowestGrade
 highestGrade } 
}`;
        return this.post({ query, variables: {  } });
    }

}
