/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";

export class ServerDao extends GraphDao {
    
    /**
     * Get server type such as MODE-PRODUCTION, MODE-DEV, MODE-ACCEPTANCE, MODE-TEST
     * */
    public getMode = (): Promise<string> => {
        const query = `query server_getMode {
    server_getMode
     { undefined } 
}`;
        return this.post({ query, variables: {  } });
    }

    
    /**
     * Returns the state of the service, to indicate if it&#x27;s closed for maintenance
     * */
    public getServerStatus = (municipality: string): Promise<string> => {
        const query = `query server_getServerStatus($municipality: String) {
    server_getServerStatus(municipality: $municipality)
     { undefined } 
}`;
        return this.post({ query, variables: { municipality: municipality } });
    }

}
