/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { GraphDao } from "./graph-dao";
import { IUser } from "./interfaces/user.generated"; 

export class UserDao extends GraphDao {
    
    /**
     * Get user given userSsn, requires operator right
     * */
    public getUser(userSsn: string): Promise<IUser> {
        const query = `query user_getUser($userSsn: String) {
    user_getUser(userSsn: $userSsn)
     { userSsn
 blocked
 createdAt
 email
 phone
 firstName
 lastName
 loginTime
 comment
 location
 occupation
 avatar
 workplace } 
}`;
        return this.post({ query, variables: { userSsn: userSsn } });
    }

    
    /**
     * Returns all users, requires operator right
     * */
    public listAll(): Promise<IUser[]> {
        const query = `query user_listAll {
    user_listAll
     { userSsn
 blocked
 createdAt
 email
 phone
 firstName
 lastName
 loginTime
 comment
 location
 occupation
 avatar
 workplace } 
}`;
        return this.post({ query, variables: {  } });
    }

}
