/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IChainSchool {
  placementRoundId?: number;
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  recievingSchoolName?: string;
  recievingSchoolProgram?: string;
  recievingGrade?: number;
}
