/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IChoice {
  choiceId?: number;
  createdAt?: Date;
  createdBy?: string;
  placementRoundId?: number;
  studentSsn?: string;
  manualInput?: boolean;
  approvedParent1?: Date;
  approvedParent2?: Date;
  manuallyApprovedBy?: string;
  language?: string;
  afterSchool?: string;
}
