/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { IViewFullChoiceRanking } from "./view-full-choice-ranking.generated";
export interface IChoiceWithRanks {
	choiceId?: number;
	createdAt?: string;
	parentSsn?: string;
	studentSsn?: string;
	studentFirstName?: string;
	studentLastName?: string;
	parentFirstName?: string;
	parentLastName?: string;
	rankings?: IViewFullChoiceRanking[];
}