/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IChoiceRanking {
  choice?: number;
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  ranking?: number;
}
