/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { TEMPLATE_MEDIUM } from "../enums/template-medium.generated"
export interface ICommunicationTemplate {
  templateName?: string;
  createdAt?: Date;
  createdBy?: string;
  description?: string;
  templateMedium?: TEMPLATE_MEDIUM;
  parentOrganization?: string;
  subject?: string;
  corpus?: string;
  preferedSchemaName?: string;
  templateFile?: number;
  emailToAddress?: string;
  emailCcAddress?: string;
  phone?: string;
  phoneCc?: string;
  name?: string;
  coAddress?: string;
  address?: string;
  zipcode?: string;
  city?: string;
}
