/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ICommunicationTrigger {
  triggerName?: string;
  description?: string;
  jsonSchema?: string;
  entryPoint?: string;
  sampleData?: string;
}
