/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { COMMENT_PARENT_TYPE } from "../enums/comment-parent-type.generated"
export interface IComment {
  commentId?: number;
  createdAt?: Date;
  createdBy?: string;
  municipality?: string;
  commentParentType?: COMMENT_PARENT_TYPE;
  commentParentId?: string;
  corpus?: string;
  deleted?: Date;
}
