/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ICommunicationTriggerAction {
  municipality?: string;
  triggerName?: string;
  templateName?: string;
  createdBy?: string;
  createdAt?: Date;
}
