/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IDistance {
  schoolMunicipality?: string;
  schoolName?: string;
  studentSsn?: string;
  distance?: number;
  routing?: string;
}
