/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { IParent } from "./parent.generated";
import { IUser } from "./user.generated";
import { IUserRight } from "./user-right.generated";
export interface ILoginInformation {
	parent?: IParent;
	ssn?: string;
	user?: IUser;
	userRights?: IUserRight[];
}