/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { IParent } from "./parent.generated"
import { ISecurityGroupMember } from "./security-group-member.generated"
import { IUser } from "./user.generated"
export interface ILoginInformation {
  parent?: IParent;
  securityGroups?: ISecurityGroupMember;
  securityRights?: string;
  user?: IUser;
}
