/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IMunicipality {
  municipalityName?: string;
  county?: string;
  longName?: string;
  isCustomer?: boolean;
  openingTime?: Date;
  closingTime?: Date;
  frontPageState?: string;
}
