/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IMunicipalityTimelineEvent {
  municipalityName?: string;
  timelineIndex?: number;
  datum?: Date;
  label?: string;
  description?: string;
}
