/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IMunicipalityAddress {
  municipalityName?: string;
  address?: string;
  city?: string;
  zipcode?: string;
  lat?: number;
  lng?: number;
}
