/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { ISchoolProgramInput } from "./school-program-input.generated"
export interface INewChoiceInputType {
  afterSchool?: string;
  language?: string;
  placementRoundId?: number;
  rankings?: ISchoolProgramInput;
  studentSsn?: string;
}
