/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IParentContactDetail {
  municipality?: string;
  parentSsn?: string;
  createdAt?: Date;
  createdBy?: string;
  phone?: string;
  email?: string;
}
