/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IParent {
	parentSsn?: string;
	createdAt?: string;
	address?: string;
	address2?: string;
	zipcode?: string;
	city?: string;
	firstName?: string;
	lastName?: string;
	email?: string;
	phone?: string;
	lat?: number;
	lng?: number;
}