/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { PARENT_CREATED_VIA } from "../enums/parent-created-via.generated"
export interface IParent {
  parentSsn?: string;
  createdAt?: Date;
  createdBy?: string;
  parentCreatedVia?: PARENT_CREATED_VIA;
  firstName?: string;
  lastName?: string;
  coAddress?: string;
  address?: string;
  zipcode?: string;
  city?: string;
  addressMunicipality?: string;
}
