/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { PARTICIPANT_TYPE } from "../enums/participant-type.generated"
export interface IParticipant {
  placementRoundId?: number;
  studentSsn?: string;
  schoolTransportSchool?: string;
  schoolTransportProgram?: string;
  catchmentSchool?: string;
  catchmentProgram?: string;
  currentGrade?: number;
  placingGrade?: number;
  inSpecialAdmissionRegion?: boolean;
  isNewlyArrived?: boolean;
  currentSchoolMunicipality?: string;
  currentSchoolName?: string;
  currentSchoolProgram?: string;
  currentPreSchoolMunicipality?: string;
  currentPreSchool?: string;
  participantType?: PARTICIPANT_TYPE;
  placementAddress?: string;
  placementZipcode?: string;
  placementCity?: string;
  placementAddressMunicipality?: string;
  placementLat?: number;
  placementLng?: number;
  limitedParticipation?: boolean;
  municipalityCaseId?: string;
  isVoucherSchoolOnly?: boolean;
}
