/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IPlacementRound {
  placementRoundId?: number;
  municipality?: string;
  createdAt?: Date;
  createdBy?: string;
  roundName?: string;
  roundDescription?: string;
  dataLockTime?: Date;
  frontpageOpenTime?: Date;
  frontpageCloseTime?: Date;
}
