/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IPriorityGround {
  placementRoundId?: number;
  studentSsn?: string;
  schoolProgram?: string;
  grade?: number;
  schoolMunicipality?: string;
  priorityGroup?: number;
  priorityGroupDescription?: string;
  hasSiblingPriority?: boolean;
  hasCompleteChoice?: boolean;
  distance?: number;
  relativeDistance?: number;
  alternativeSchool?: string;
  distanceAlternativeSchool?: number;
  lotteryNumberSimple?: number;
  createdAt?: Date;
  distanceCutOff?: boolean;
  isEligible?: boolean;
  rank?: number;
  rankGroup?: number;
  rankGroupDescription?: string;
  rankLength?: number;
}
