/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IPrivateSchoolAdmission {
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  studentSsn?: string;
  firstName?: string;
  lastName?: string;
  admissionStatus?: string;
  priority?: number;
  placingGrade?: number;
}
