/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IRestrictedChoosability {
  placementRoundId?: number;
  studentSsn?: string;
  schoolName?: string;
  schoolProgram?: string;
  grade?: number;
}
