/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ISchool {
	schoolId?: number;
	name?: string;
	municipality?: string;
	area?: string;
	address?: string;
	address2?: string;
	zipcode?: string;
	city?: string;
	info?: string;
	lat?: number;
	lng?: number;
	statute?: string;
	specialProgram?: boolean;
	homepage?: string;
	lowestGrade?: number;
	highestGrade?: number;
}