/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ISchool {
  schoolMunicipality?: string;
  schoolName?: string;
  coAddress?: string;
  address?: string;
  zipcode?: string;
  city?: string;
  info?: string;
  lat?: number;
  lng?: number;
  isVoucherSchool?: boolean;
  homepage?: string;
  email?: string;
  phone?: string;
  municipalitySchoolId?: string;
  nationalSchoolId?: string;
}
