/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ISchoolProgram {
  placementRoundId?: number;
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  isSpecialProgram?: boolean;
  lowestGrade?: number;
  highestGrade?: number;
}
