/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ISchoolProgramGrade {
  placementRoundId?: number;
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  grade?: number;
  capacity?: number;
  choosable?: boolean;
  restrictedChoosability?: boolean;
}
