/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ISecurityRight {
  securityRight?: string;
  endpoint?: string;
  description?: string;
  authType?: string;
  sensitivity?: string;
  namespace?: string;
  mutating?: boolean;
}
