/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ISentEmail {
  emailId?: number;
  createdAt?: Date;
  createdBy?: string;
  from?: string;
  toAddress?: string;
  cc?: string;
  bcc?: string;
  subject?: string;
  htmlBody?: string;
  plainText?: string;
  parentObjectType?: string;
  parentObjectId?: string;
  templateUsed?: string;
  messageId?: string;
  account?: string;
}
