/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ISentLetter {
  letterId?: number;
  createdAt?: Date;
  createdBy?: string;
  name?: string;
  coAddress?: string;
  address?: string;
  zipcode?: string;
  city?: string;
  htmlContent?: string;
  campaignId?: string;
  envelopeId?: string;
  numPage?: number;
  priorityClass?: string;
  uploadedFileId?: number;
  parentObjectType?: string;
  parentObjectId?: string;
  account?: string;
}
