/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { FLAG } from "../enums/flag.generated"
export interface ISibling {
  placementRoundId?: number;
  studentSsn?: string;
  siblingSsn?: string;
  createdAt?: Date;
  firstName?: string;
  lastName?: string;
  schoolName?: string;
  schoolMunicipality?: string;
  schoolProgram?: string;
  grade?: number;
  handledBy?: string;
  flag?: FLAG;
}
