/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface ISpecialProgramPriority {
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  studentSsn?: string;
  priority?: number;
}
