/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IStudent {
	studentSsn?: string;
	createdAt?: string;
	firstName?: string;
	lastName?: string;
	parent1?: string;
	parent2?: string;
	address?: string;
	address2?: string;
	zipcode?: string;
	city?: string;
	municipality?: string;
	area?: string;
	grade?: number;
	currentSchool?: number;
	canContinue?: boolean;
	lat?: number;
	lng?: number;
}