/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IStudentLog {
  studentLogId?: number;
  municipality?: string;
  studentSsn?: string;
  createdAt?: Date;
  createdBy?: string;
  createdByParent?: boolean;
  eventType?: string;
  eventBodyJson?: string;
  userComment?: string;
  fileId?: number;
  severityLevel?: number;
}
