/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { SYSTEM } from "../enums/system.generated"
export interface ITranslationDefault {
  system?: SYSTEM;
  language?: string;
  labelKey?: string;
  translation?: string;
}
