/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { IViewParentContactDetails } from "./view-parent-contact-details.generated"
import { IParticipant } from "./participant.generated"
import { IPlacementRound } from "./placement-round.generated"
import { IStudent } from "./student.generated"
export interface ITriggerBase {
  parent1?: IViewParentContactDetails;
  parent2?: IViewParentContactDetails;
  participant?: IParticipant;
  placementRound?: IPlacementRound;
  student?: IStudent;
}
