/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IUploadChoice {
  placementRoundId?: number;
  ranking?: number;
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  studentSsn?: string;
}
