/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IUploadInputType {
  name?: string;
  content?: string;
  mimeType?: string;
  size?: number;
  isZipped?: boolean;
}
