/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IUser {
  username?: string;
  userSsn?: string;
  blocked?: boolean;
  createdAt?: Date;
  municipality?: string;
  email?: string;
  phone?: string;
  firstName?: string;
  lastName?: string;
  loginTime?: Date;
  comment?: string;
  location?: string;
  occupation?: string;
  avatar?: string;
  workplace?: string;
  lastSeen?: Date;
  language?: string;
}
