/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IUser {
	userSsn?: string;
	blocked?: boolean;
	createdAt?: string;
	email?: string;
	phone?: string;
	firstName?: string;
	lastName?: string;
	loginTime?: string;
	comment?: string;
	location?: string;
	occupation?: string;
	avatar?: string;
	workplace?: string;
}