/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewPrivateSchoolAdmission {
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  studentSsn?: string;
  firstName?: string;
  lastName?: string;
  admissionStatus?: string;
  priority?: number;
  placingGrade?: number;
  isMatched?: number;
  numPlacements?: number;
  isDoublePlaced?: number;
}
