/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewLastChoiceRanking {
  choiceId?: number;
  placementRoundId?: number;
  studentSsn?: string;
  createdAt?: Date;
  placingGrade?: number;
  studentFirstName?: string;
  studentLastName?: string;
  municipality?: string;
  language?: string;
  afterSchool?: string;
  choice?: number;
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  ranking?: number;
}
