/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewLastChoice {
  choiceId?: number;
  createdAt?: Date;
  createdBy?: string;
  placementRoundId?: number;
  studentSsn?: string;
  manualInput?: boolean;
  approvedParent1?: Date;
  approvedParent2?: Date;
  manuallyApprovedBy?: string;
  language?: string;
  afterSchool?: string;
  studentFirstName?: string;
  studentLastName?: string;
  currentGrade?: number;
  placingGrade?: number;
  municipality?: string;
  parentCount?: number;
  isApproved?: number;
}
