/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewTextMessage {
  textMessageId?: number;
  createdAt?: Date;
  createdBy?: string;
  phoneNumber?: string;
  message?: string;
  parentObjectType?: string;
  parentObjectId?: string;
  account?: string;
  response?: string;
  firstName?: string;
  lastName?: string;
  municipality?: string;
}
