/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { TEMPLATE_MEDIUM } from "../enums/template-medium.generated"
export interface IViewTriggerWiring {
  triggerName?: string;
  description?: string;
  jsonSchema?: string;
  entryPoint?: string;
  sampleData?: string;
  createdAt?: Date;
  createdBy?: string;
  municipality?: string;
  templateName?: string;
  corpus?: string;
  parentOrganization?: string;
  subject?: string;
  templateMedium?: TEMPLATE_MEDIUM;
  isBroken?: number;
}
