/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewFullChoiceRanking {
	choice?: number;
	school?: number;
	rank?: number;
	schoolId?: number;
	name?: string;
	municipality?: string;
	area?: string;
	address?: string;
	zipcode?: string;
	city?: string;
	info?: string;
	lat?: number;
	lng?: number;
	statute?: string;
	specialProgram?: boolean;
	homepage?: string;
	lowestGrade?: number;
	highestGrade?: number;
	studentSsn?: string;
}