/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewParentInconsistency {
  parentSsn?: string;
  studentSsn?: string;
  studentMunicipality?: string;
  userSsn?: string;
  userMunicipality?: string;
}
