/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewRankingChoiceDistribution {
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  placingGrade?: number;
  ranking?: number;
  capacity?: number;
  numItems?: number;
}
