/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { CREATED_VIA } from "../enums/created-via.generated"
import { NAVET_LOOKUP_STATUS } from "../enums/navet-lookup-status.generated"
export interface IViewPotentialNewParticipants {
  placementRoundId?: number;
  municipality?: string;
  studentSsn?: string;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: string;
  createdVia?: CREATED_VIA;
  lockNavetUpdates?: boolean;
  navetLookupStatus?: NAVET_LOOKUP_STATUS;
  lotteryNumber?: string;
  debugHelpColumn?: string;
  isTestKid?: boolean;
  firstName?: string;
  lastName?: string;
  parent1?: string;
  parent2?: string;
  coAddress?: string;
  address?: string;
  zipcode?: string;
  city?: string;
  addressMunicipality?: string;
  lat?: number;
  lng?: number;
  hasApprovedOptOut?: number;
}
