/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { PARTICIPANT_TYPE } from "../enums/participant-type.generated"
export interface IViewLastChoiceView {
  choiceId?: number;
  studentFirstName?: string;
  studentLastName?: string;
  language?: string;
  afterSchool?: string;
  municipality?: string;
  isApproved?: number;
  address?: string;
  zipcode?: string;
  coAddress?: string;
  city?: string;
  parent1?: string;
  parent2?: string;
  placementRoundId?: number;
  studentSsn?: string;
  schoolTransportSchool?: string;
  schoolTransportProgram?: string;
  catchmentSchool?: string;
  catchmentProgram?: string;
  placingGrade?: number;
  inSpecialAdmissionRegion?: boolean;
  isNewlyArrived?: boolean;
  currentSchoolMunicipality?: string;
  currentSchoolName?: string;
  currentSchoolProgram?: string;
  currentPreSchoolMunicipality?: string;
  currentPreSchool?: string;
  participantType?: PARTICIPANT_TYPE;
  placementAddress?: string;
  placementZipcode?: string;
  placementCity?: string;
  choice?: number;
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  ranking?: number;
}
