/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { PARTICIPANT_TYPE } from "../enums/participant-type.generated"
export interface IViewParticipantDisplay {
  placementRoundId?: number;
  studentSsn?: string;
  schoolTransportSchool?: string;
  schoolTransportProgram?: string;
  catchmentSchool?: string;
  catchmentProgram?: string;
  placingGrade?: number;
  inSpecialAdmissionRegion?: boolean;
  isNewlyArrived?: boolean;
  currentSchoolMunicipality?: string;
  currentSchoolName?: string;
  currentSchoolProgram?: string;
  currentPreSchoolMunicipality?: string;
  currentPreSchool?: string;
  placementAddress?: string;
  placementZipcode?: string;
  placementCity?: string;
  placementAddressMunicipality?: string;
  participantType?: PARTICIPANT_TYPE;
  limitedParticipation?: boolean;
  municipalityCaseId?: string;
  municipality?: string;
  createdAt?: Date;
  firstName?: string;
  lastName?: string;
  parent1?: string;
  parent2?: string;
  coAddress?: string;
  address?: string;
  zipcode?: string;
  city?: string;
  addressMunicipality?: string;
  currentGrade?: number;
  lotteryNumber?: string;
  lat?: number;
  lng?: number;
  debugHelpColumn?: string;
  hasCompleteChoice?: number;
  parent1FirstName?: string;
  parent1LastName?: string;
  parent1CoAddress?: string;
  parent1Address?: string;
  parent1Zipcode?: string;
  parent1City?: string;
  parent2FirstName?: string;
  parent2LastName?: string;
  parent2CoAddress?: string;
  parent2Address?: string;
  parent2Zipcode?: string;
  parent2City?: string;
  parent1Phone?: string;
  parent1Email?: string;
  parent2Phone?: string;
  parent2Email?: string;
  optOut?: string;
  numChoicesMade?: number;
}
