/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { PARTICIPANT_TYPE } from "../enums/participant-type.generated"
import { CREATED_VIA } from "../enums/created-via.generated"
import { NAVET_LOOKUP_STATUS } from "../enums/navet-lookup-status.generated"
export interface IViewParticipantWithStudent {
  placementRoundId?: number;
  studentSsn?: string;
  schoolTransportSchool?: string;
  schoolTransportProgram?: string;
  catchmentSchool?: string;
  catchmentProgram?: string;
  currentGrade?: number;
  placingGrade?: number;
  inSpecialAdmissionRegion?: boolean;
  isNewlyArrived?: boolean;
  currentSchoolMunicipality?: string;
  currentSchoolName?: string;
  currentSchoolProgram?: string;
  currentPreSchoolMunicipality?: string;
  currentPreSchool?: string;
  participantType?: PARTICIPANT_TYPE;
  placementAddress?: string;
  placementZipcode?: string;
  placementCity?: string;
  placementAddressMunicipality?: string;
  placementLat?: number;
  placementLng?: number;
  limitedParticipation?: boolean;
  municipalityCaseId?: string;
  isVoucherSchoolOnly?: boolean;
  municipality?: string;
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: string;
  createdVia?: CREATED_VIA;
  lockNavetUpdates?: boolean;
  navetLookupStatus?: NAVET_LOOKUP_STATUS;
  lotteryNumber?: string;
  debugHelpColumn?: string;
  isTestKid?: boolean;
  firstName?: string;
  lastName?: string;
  parent1?: string;
  parent2?: string;
  coAddress?: string;
  address?: string;
  zipcode?: string;
  city?: string;
  addressMunicipality?: string;
  lat?: number;
  lng?: number;
}
