/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewMoveRequestParentInfo {
	moveRequestId?: number;
	createdAt?: string;
	createdBy?: string;
	studentSsn?: string;
	fileId?: number;
	address?: string;
	address2?: string;
	zipcode?: string;
	city?: string;
	requestStatus?: string;
	userComment?: string;
	canceled?: string;
	phone?: string;
	email?: string;
	firstName?: string;
	lastName?: string;
	userFirstName?: string;
	userLastName?: string;
}