/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */

export interface IViewParent {
  parentSsn?: string;
  createdAt?: Date;
  firstName?: string;
  lastName?: string;
  coAddress?: string;
  address?: string;
  zipcode?: string;
  city?: string;
  email?: string;
  phone?: string;
  municipality?: string;
}
