/**
 * Autogenerated interface, DO NOT MODIFY
 */
/* tslint:disable */
import { PARTICIPANT_TYPE } from "../enums/participant-type.generated"
import { PLACEMENT_STATUS } from "../enums/placement-status.generated"
import { APPROVED_PARENT1 } from "../enums/approved-parent1.generated"
import { APPROVED_PARENT2 } from "../enums/approved-parent2.generated"
export interface IViewParticipantWithPlacements {
  placementRoundId?: number;
  studentSsn?: string;
  schoolTransportSchool?: string;
  schoolTransportProgram?: string;
  catchmentSchool?: string;
  catchmentProgram?: string;
  currentGrade?: number;
  placingGrade?: number;
  inSpecialAdmissionRegion?: boolean;
  isNewlyArrived?: boolean;
  currentSchoolMunicipality?: string;
  currentSchoolName?: string;
  currentSchoolProgram?: string;
  currentPreSchoolMunicipality?: string;
  currentPreSchool?: string;
  participantType?: PARTICIPANT_TYPE;
  placementAddress?: string;
  placementZipcode?: string;
  placementCity?: string;
  placementAddressMunicipality?: string;
  placementLat?: number;
  placementLng?: number;
  limitedParticipation?: boolean;
  municipalityCaseId?: string;
  isVoucherSchoolOnly?: boolean;
  municipality?: string;
  firstName?: string;
  lastName?: string;
  placementIndex?: number;
  createdAt?: Date;
  schoolMunicipality?: string;
  schoolName?: string;
  schoolProgram?: string;
  placementStatus?: PLACEMENT_STATUS;
  approvedParent1?: APPROVED_PARENT1;
  approvedParent2?: APPROVED_PARENT2;
  manuallyApprovedBy?: string;
  expires?: Date;
  priorityGroup?: number;
  priorityGroupDescription?: string;
  hasSiblingPriority?: boolean;
  hasCompleteChoice?: boolean;
  distance?: number;
  relativeDistance?: number;
  alternativeSchool?: string;
  distanceAlternativeSchool?: number;
  lotteryNumberSimple?: number;
  distanceCutOff?: boolean;
  priorityScore?: number;
  currrentPreSchool?: string;
  appealNumber?: number;
}
